apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: alert
    role: alert-rules
  name: prometheus-alert-rules
  namespace: openshift-storage
spec:
  groups:
  - name: cluster-state-alert.rules
    rules:
    - alert: CephClusterErrorState
      annotations:
        description: Storage cluster is in error state for more than 10m.
        message: Storage cluster is in error state
        severity_level: error
        storage_type: ceph
      expr: |
        ceph_health_status{job="rook-ceph-mgr"} > 1
      for: 10m
      labels:
        severity: critical
    - alert: CephClusterWarningState
      annotations:
        description: Storage cluster is in warning state for more than 10m.
        message: Storage cluster is in warning state
        severity_level: warning
        storage_type: ceph
      expr: |
        ceph_health_status{job="rook-ceph-mgr"} == 1
      for: 10m
      labels:
        severity: warning
<<<<<<< HEAD
  - name: cluster-utilization-alert.rules
    rules:
    - alert: CephClusterNearFull
      annotations:
        description: The utilization of storage cluster has crossed 85%.
        message: Storage cluster is nearing full. An expansion is required
        severity_level: warning
        storage_type: ceph
      expr: |
        sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.85
      for: 5m
      labels:
        severity: warning
    - alert: CephClusterCriticallyFull
      annotations:
        description: The utilization of storage cluster has crossed 95%.
        message: Storage cluster is critically full and needs immediate expansion
        severity_level: error
        storage_type: ceph
      expr: |
        sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.95
      for: 5m
      labels:
        severity: critical
  - name: quorum-alert.rules
    rules:
    - alert: MonQuorumAtRisk
      annotations:
        description: Quorum is low for storage cluster. Please Contact Support
        message: Storage quorum at risk
        severity_level: warning
        storage_type: ceph
      expr: |
        count(ceph_mon_quorum_status == 1) <= ((count(ceph_mon_metadata) % 2) + 1)
      for: 15m
      labels:
        severity: warning
=======
  - name: pg-alert.rules
    rules:
    - alert: OCS_CephPgStuck
      annotations:
        message: OCS Ceph PG's in stuck state. Recommended for Admin to review the
          cluster.
      expr: |
        max(ceph_osd_numpg{job="rook-ceph-mgr"}) - scalar(ceph_pg_active{job="rook-ceph-mgr"}) <= 0
      for: 1m
      labels:
        severity: error
>>>>>>> Added alert for ceph pg stuck
