apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: alert
    role: alert-rules
  name: prometheus-alert-rules
  namespace: openshift-storage
spec:
  groups:
  - name: clock-alert.rules
    rules:
    - alert: ClockSkew
      annotations:
        description: Clock skew detected on {{ $labels.host }}. Please confirm NTP
          is configured correctly on this host
        message: Clock skew/drift detected
        severity_level: warning
        storage_type: ceph
      expr: |
        label_replace((node_ntp_offset_seconds < -0.03 or node_ntp_offset_seconds > 0.03),"host","$1","instance","(.*):.*")
      for: 30s
      labels:
        severity: warning
  - name: cluster-state-alert.rules
    rules:
    - alert: CephClusterErrorState
      annotations:
        description: Storage cluster is in error state for more than 10m.
        message: Storage cluster is in error state
        severity_level: error
        storage_type: ceph
      expr: |
        ceph_health_status{job="rook-ceph-mgr"} > 1
      for: 10m
      labels:
        severity: critical
    - alert: CephClusterWarningState
      annotations:
        description: Storage cluster is in warning state for more than 10m.
        message: Storage cluster is in warning state
        severity_level: warning
        storage_type: ceph
      expr: |
        ceph_health_status{job="rook-ceph-mgr"} == 1
      for: 10m
      labels:
        severity: warning
  - name: cluster-utilization-alert.rules
    rules:
    - alert: CephClusterNearFull
      annotations:
        description: The utilization of storage cluster has crossed 85%.
        message: Storage cluster is nearing full. An expansion is required
        severity_level: warning
        storage_type: ceph
      expr: |
        sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.85
      for: 5m
      labels:
        severity: warning
    - alert: CephClusterCriticallyFull
      annotations:
        description: The utilization of storage cluster has crossed 95%.
        message: Storage cluster is critically full and needs immediate expansion
        severity_level: error
        storage_type: ceph
      expr: |
        sum(ceph_osd_stat_bytes_used) / sum(ceph_osd_stat_bytes) > 0.95
      for: 5m
      labels:
        severity: critical
  - name: quorum-alert.rules
    rules:
    - alert: MonQuorumAtRisk
      annotations:
        description: Quorum is low for storage cluster. Please Contact Support
        message: Storage quorum at risk
        severity_level: warning
        storage_type: ceph
      expr: |
        count(ceph_mon_quorum_status == 1) <= ((count(ceph_mon_metadata) % 2) + 1)
      for: 15m
      labels:
        severity: warning
